### PR TITLE
Revert "add Alex Waite to authors list"

### PR DESCRIPTION
**Pull request by aqw**
This reverts commit b3d1a8b4442a8f5cf6da7a8b1d437e388cd7759c.

Removing myself from the author list. There are aspects of DataLad ecosystem that I have meaningfully contributed to, but seem to fall outside of the intended scope/direction of the current paper.

### CODE REVIEW

**Comment by yarikoptic** [comment]
Would you mind to be acknowledged? then please do not introduced commented out section (or I will pester you again) and add your name to the acknowledgement list. or let me know and I would do all that

**Comment by aqw** [comment]
I'm fine with being in the acknowledgements section.

I can certainly update the PR, but it seems like there's an organization syntax you're using overlaid on markdown. Please feel free to make the changes as you wish, or explain to me how you would like the syntax to be.

**Comment by yarikoptic** [comment]
no worries, I will do it then

**Comment by aqw** [comment]
Thanks. :-)

**Pull request merged**
